### PR TITLE
Fix-82: Remove argument `use.tripack`

### LINKED ISSUE #82: Deprecated `use.tripack = TRUE`
image

In `?panel.voronoi`:

> Details  
> Up to version 0.6-29, latticeExtra used the deldir package to compute the Voronoi mosaic by default, while offering the choice of using the faster but non-free ACM licensed implementation in the tripack package by setting use.tripack = TRUE. Later versions use the FOSS replacements in interp by default, and deprecates the use.tripack argument. The deldir implementation, which allows polygons to be clipped to a rectangular window (the win.expand argument), can still be used using backend = "deldir".

### LINKED ISSUE #89: Error in `.options[[name]]`: missing subscript (in R-devel)
With R devel, there is an issue  
```
Error in `.options[[name]]`: missing subscript
```

image

### PR DESCRIPTION
**Pull request by GegznaV**
- Closes #82.

UPDATE: 

- after merging https://github.com/r-hyperspec/hyperSpec/pull/81, should also address #80 (part related to `hyperSpec`)
- after merging https://github.com/r-hyperspec/hyperSpec/pull/88, fixes #89

### CODE REVIEW

**Comment by GegznaV** [comment]
It fails on Linux only and I cannot understand why. @cbeleites, can you look into this? There is a message "Killed" that is not informative.

<details>
image

image

</details>

File: R/plot_map.R [hunk 1]
```diff
@@ -97,14 +94,6 @@
 #' # Voronoi plots
 #' smpl <- sample(faux_cell, 300)
 #' plotmap(smpl, region ~ x * y)
-#' if (require(tripack)) {
```
Comment (cbeleites) [inline R/plot_map.R:100]: btw, we could leave the `plotvoronoi()` example without further arguments in here since we anyways import from **latticeExta**.

File: R/plot_voronoi.R [hunk 2]
```diff
@@ -39,18 +36,20 @@ plotvoronoi <- function(object, model = spc ~ x * y,
...
-  if (use.tripack) {
-    if (!requireNamespace("tripack")) {
-      stop("package tripack requested but not available.")
-    }
-  } else {
-    if (!requireNamespace("deldir")) {
-      stop("package deldir requested but not available.")
-    }
+  if (!(use.tripack == FALSE)) {
+    warning(paste0(
```
Comment (cbeleites) [inline R/plot_voronoi.R]: @GegznaV what do you think of removing the default `FALSE` for the deprecated arguments and then checking `if(!missing(use.tripack))` etc.?

Comment (cbeleites) [inline R/plot_voronoi.R]: `warning()` already `paste0()`s multiple arguments

Comment (GegznaV) [reply R/plot_voronoi.R]: Excellent idea.

Comment (GegznaV) [reply R/plot_voronoi.R]: I fixed that

File: R/plot_map.R (hunk 1 above)
Comment (GegznaV) [reply R/plot_map.R:100]: The example is now present again.

**Comment by GegznaV** [comment]
- [x] Blocked ⛔ until #88 is merged into this PR.

**Comment by GegznaV** [comment]
@cbeleites, can this PR be merged now? It solves a few issues related to R4.2.0, R-devel and **latticeExtra**.

**Review by cbeleites — APPROVED** [review]
Hi @GegznaV, many thanks for taking care of this
